[meta]
name     = "Race Stats"
author   = "XertroV"
category = "MLHook"
version  = "0.1.0"

[script]
#__DEFINES__
# dependencies = ["MLHook", "VehicleState"]
dependencies = ["MLHook", "Camera", "VehicleState"]
